foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about-author/", views.flatpage,
         {"url": "/about-author/"}, name="about-author"),
    path("about-spec/", views.flatpage,
         {"url": "/about-spec/"}, name="about-spec"),
    path("about/", include("django.contrib.flatpages.urls")),
    path("", include("recipes.urls")),
    path("", include("users.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path("auth/signup/", views.SignUp.as_view(), name="signup"),
    path("auth/", include("django.contrib.auth.urls")),
    path("<username>/", views.profile, name="profile"),
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Tag(models.Model):
    name = models.TextField(verbose_name='Название тега')
    slug = models.SlugField(verbose_name='Тэг', unique=True, max_length=100,)
    style = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.slug


class Ingredient(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    dimension = models.CharField(
        max_length=100, blank=True, null=True,
        verbose_name='Единицы измерения')

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'
        ordering = ('name', )

    def __str__(self):
        return self.name


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipes',
                               verbose_name='Автор публикации',)
    name = models.CharField(verbose_name='Название рецепта', max_length=200)
    image = models.ImageField(upload_to='recipes/',)
    description = models.CharField(max_length=280)
    ingredients = models.ManyToManyField(
        Ingredient, related_name='recipes',
        through='IngredientRecipe',
        through_fields=('recipe', 'ingredient'),
    )
    tag = models.ManyToManyField(
        Tag, related_name='recipes', verbose_name='Теги')
    time = models.PositiveIntegerField(
        verbose_name='Время приготовления в минутах')
    slug = models.SlugField(
        verbose_name='URL slug',
        unique=True,
        blank=True, null=True
    )
    pub_date = models.DateField(
        verbose_name='Дата публикации', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-pub_date', )


class IngredientRecipe(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, blank=True, null=True)
    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.PositiveSmallIntegerField(
        verbose_name='Количество', default=0, blank=True, null=True)

    def __str__(self):
        return f'{self.ingredient} для {self.recipe}'


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='follower')
    author = models.ManyToManyField(
        User, related_name='following',
        verbose_name='Избранный автор', blank=True)

    def __str__(self):
        return f'Подписки {self.user}'

    class Meta:
        verbose_name = 'Подписка на автора'
        verbose_name_plural = 'Подписки на авторов'


class Favorite(models.Model):
    recipes = models.ManyToManyField(
        Recipe, related_name='favorites', verbose_name='Рецепты', blank=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='favorites')

    def __str__(self):
        return f'Избранные рецепты {self.user}'

    class Meta:
        verbose_name = 'Избранный рецепт'
        verbose_name_plural = 'Избранные рецепты'


class ShopList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='shop_lists',
                             verbose_name='Пользователь')
    recipes = models.ManyToManyField(
        Recipe, related_name='shop_lists', verbose_name='Рецепты', blank=True)

    def __str__(self):
        return f'Список покупок {self.user}'

    class Meta:
        verbose_name = 'Список покупок'
        verbose_name_plural = 'Списки покупок'

templates/authorRecipe.html
{% extends "base.html" %}
{% block title %} Рецепты {% endblock %}
{% block main_title %}
<div class="main__header">
  <h1 class="main__title">{{ author }}</h1>
{% endblock %}

{% block static_stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static './pages/index.css' %}">
{% endblock static_stylesheet %}

{% block menu %}
{% include "menu.html" with index=True %}
{% endblock %}

{% load recipe_tag %}
{% block tags %}
<ul class="tags">
  {% with filter_values=request.GET|tag_values %}
  {% for tag in tags %}
    <li class="tags__item">
      <a id='{{ tag.slug }}'
      class="tags__checkbox tags__checkbox_style_{{ tag.style }} {% if tag.slug in filter_values %}tags__checkbox_active{% endif %}"
      href="{% url 'profile' author %}?{{request|tag_link:tag }}">    
      </a>
      <span class="tags__label">{{ tag.name }}</span>
    </li>
  {% endfor %}
  {% endwith %}
</ul>
</div>
{% endblock %}

{% block content %}
<div class="container"></div>
  {% if user.is_authenticated %}
    {% if user != author %}
      <div class="author-subscribe" data-author="{{ author.id }}">
        {% if author in subscriptions %}
          <p style="padding: 0 0 2em 0;">
          <button class="button button_style_light-blue button_size_subscribe button_style_blue"
          name="subscribe">Отписаться от автора</button></p>
        {% else %}
          <p style="padding: 0 0 2em 0;">
          <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
        {% endif %}
      </div>
    {% endif %}
  {% endif %}
<div class="card-list">
  {% for recipe in page %}
    {% include "recipe_item.html" with recipe=recipe %}
  {% endfor %}
</div>
<nav class="pagination" aria-label="Search results pages">
  <ul class="pagination__container">
    {% if page.has_other_pages %}
      {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
  </ul>
</nav>
</div>
{% endblock %}

{% block scripts_js %}
<script src="{% static './js/components/MainCards.js' %}"></script>
<script src="{% static './js/components/Purchases.js' %}"></script>
<script src="{% static './js/components/Favorites.js' %}"></script>
<script src="{% static './js/components/Subscribe.js' %}"></script>
<script src="{% static './js/config/config.js' %}"></script>
<script src="{% static './js/components/AuthorRecipe.js' %}"></script>
<script src="{% static './js/components/Header.js' %}"></script>
<script src="{% static './js/api/Api.js' %}"></script>
<script src="{% static 'authorRecipe.js' %}"></script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Заголовок страницы{% endblock %}</title>
    {% block static_stylesheet %}{% endblock static_stylesheet %}
</head>
<body class="body">
    <header class="header">
        {% block menu %}{% endblock menu %}
        {% include 'nav.html' %}
    </header>
    <main class="main container">
        {% block main_title %}Заголовок страницы{% endblock %}
        {% block tags %}{% endblock tags %}
        {% block content %}{% endblock content %}
    </main>
    <footer class="footer">
        <div class="footer__container container">
            <a href="{% url  'index' %}" class="footer__brand link">Продуктовый помощник</a>
            <ul class="footer__items">
                <li class="footer__item"><a href="{% url  'about-author' %}" class="footer__link link">Об авторе </a></li>
                <li class="footer__item"><a href="{% url  'about-spec' %}" class="footer__link link">Технологии</a></li>
            </ul>
        </div>
    </footer>
    {% block scripts_js %}{% endblock %}
</body>
</html>

templates/favorite.html
{% extends "base.html" %}
{% block title %} Избранное  {% endblock %}

{% block main_title %}
<div class="main__header">
    <h1 class="main__title">Избранное</h1>
{% endblock %}

{% block static_stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static './pages/index.css' %}">         
{% endblock static_stylesheet %}

{% block menu %}
{% include "menu.html" with myfavorites=True %}
{% endblock %}

{% load recipe_tag %}
{% block tags %}
<ul class="tags">
    {% with filter_values=request.GET|tag_values %}
    {% for tag in tags %}
        <li class="tags__item">
            <a id='{{ tag.slug }}'
            class="tags__checkbox tags__checkbox_style_{{ tag.style }} {% if tag.slug in filter_values %}tags__checkbox_active{% endif %}"
            href="{% url 'favorites' %}?{{ request|tag_link:tag }}">
            </a>
            <span class="tags__label">{{ tag.name }}</span>
        </li>
    {% endfor %}
    {% endwith %}
</ul>
</div> 
{% endblock %}    
 
{% block content %}
<div class="container"></div>
<div class="card-list">
    {% for recipe in page %}
        {% include "recipe_item.html" with recipe=recipe %}
    {% endfor %}
</div>
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}
    </ul>
</nav> 
</div>
{% endblock %}            

{% block scripts_js %}
<script src="{% static './js/components/MainCards.js' %}"></script>   
<script src="{% static './js/components/Purchases.js' %}"></script>
<script src="{% static './js/components/Favorites.js' %}"></script>
<script src="{% static './js/components/CardList.js' %}"></script>   
<script src="{% static './js/config/config.js' %}"></script>
<script src="{% static './js/components/AuthorRecipe.js' %}"></script>
<script src="{% static './js/components/Header.js' %}"></script>   
<script src="{% static './js/api/Api.js' %}"></script>
<script src="{% static 'favorite.js' %}"></script> 
{% endblock %}

templates/indexAuth.html
{% extends "base.html" %}
{% block title %} Рецепты  {% endblock %}
{% block main_title %}
<div class="main__header">
<h1 class="main__title">
Рецепты
</h1>
{% endblock %}

{% block static_stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static './pages/index.css' %}">
{% endblock static_stylesheet %}

{% block menu %}
{% include "menu.html" with index=True %}
{% endblock %}
 
{% load recipe_tag %}
{% block tags %}
<ul class="tags">
  {% with filter_values=request.GET|tag_values %}
  {% for tag in tags %}
    <li class="tags__item">
      <a 
      id='{{ tag.slug}}'
      class="tags__checkbox tags__checkbox_style_{{ tag.style }} {% if tag.slug in filter_values %}tags__checkbox_active{% endif %}"
      href="{% url 'index' %}?{{ request|tag_link:tag }}">
      </a>
      <span class="tags__label">{{ tag.name }}</span>
    </li>
  {% endfor %}
  {% endwith %}
</ul>
</div> 
{% endblock %}    
  
<div class="container">
{% block content %} 
<div class="card-list">
  {% for recipe in page %}
    {% include "recipe_item.html" with recipe=recipe %}
  {% endfor %}
</div>
<nav class="pagination" aria-label="Search results pages">
  <ul class="pagination__container">
    {% if page.has_other_pages %}
      {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}        
  </ul>
</nav> 
</body>
{% endblock %}  
</div>
    
{% block scripts_js %}     
{% load static %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static './js/components/MainCards.js' %}"></script>
<script src="{% static './js/components/Purchases.js' %}"></script>
<script src="{% static './js/components/Favorites.js' %}"></script>
<script src="{% static './js/components/CardList.js' %}"></script>
<script src="{% static './js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'indexAuth.js' %}"></script>
{% endblock %}   

templates/indexNotAuth.html
{% extends "base.html" %}
{% block title %} Рецепты  {% endblock %}
{% block main_title %}
<div class="main__header">
  <h1 class="main__title">Рецепты</h1>
{% endblock %}

{% block static_stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static './pages/index.css' %}">
{% endblock static_stylesheet %}

{% block menu %}
{% include "menu.html" with index=True %}
{% endblock %}

{% load recipe_tag %}
{% block tags %}
<ul class="tags">     
  {% with filter_values=request.GET|tag_values %}
  {% for tag in tags %}
    <li class="tags__item">
      <a 
      id='{{ tag.slug }}'
      class="tags__checkbox tags__checkbox_style_{{ tag.style }} {% if tag.slug in filter_values %}tags__checkbox_active{% endif %}"
      href="{% url 'index' %}?{{ request|tag_link:tag }}">
      </a>
      <span class="tags__label">{{ tag.name }}</span>
    </li>
  {% endfor %}
  {% endwith %}
</ul>
</div> 
 {% endblock %}    
   
<div class="container">
{% block content %}
<div class="card-list">
  {% for recipe in page %}
    {% include "recipe_item.html" with recipe=recipe %}
  {% endfor %}
</div>
<nav class="pagination" aria-label="Search results pages">
  <ul class="pagination__container">
    {% if page.has_other_pages %}          
      {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
  </ul>
</nav>
{% endblock %}  
</div>

{% block scripts_js %}
{% load static %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static './js/components/MainCards.js' %}"></script>
<script src="{% static './js/components/Purchases.js' %}"></script>
<script src="{% static './js/components/CardList.js' %}"></script>
<script src="{% static './js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'indexNotAuth.js' %}"></script>
{% endblock %}

templates/menu.html
<nav class="nav">
    <div class="nav__container container">   
    {% if user.is_authenticated %}
        <ul class="nav__items list">
            <li class=" {% if index %} nav__item_active {% endif %} nav__item"><a href="{% url  'index' %}" class="nav__link link">Рецепты</a></li>
            <li class="{% if myfollow %} nav__item_active {% endif %} nav__item"><a href="{% url  'follow_index' %}" class="nav__link link">Мои подписки</a></li>
            <li class="{% if new_recipe %} nav__item_active {% endif %} nav__item"><a href="{% url  'new_recipe' %}" class="nav__link link">Создать рецепт</a></li>
            <li class=" {% if myfavorites %} nav__item_active  {% endif %}  nav__item  "><a href="{% url  'favorites' %}" class="nav__link link">Избранное</a></li>
            <li class="{% if purchase %} nav__item_active {% endif %} nav__item"><a href="{% url  'shops' %}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{{ shops.count }}</span></li>
        </ul>
        {% else %}
        <ul class="nav__items list">
            <li class="{% if index %} nav__item_active {% endif %} nav__item"><a href="{% url  'index' %}" class="nav__link link">Рецепты</a></li>
        </ul>
    {% endif %}

templates/myFollow.html
{% extends "base.html" %}
{% block title %} Мои подписки  {% endblock %}
{% block main_title %}
<div class="main__header">
  <h1 class="main__title">Мои подписки</h1>
</div>
{% endblock %}

{% block static_stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static './pages/myFollow.css' %}">
{% endblock static_stylesheet %} 

{% block menu %}
{% include "menu.html" with myfollow=True %}
{% endblock %}

<div class="container">
{% block content %}
<div class="card-list">
  {% if authors and recipes %}
    {% for author in authors %}
      {% include "recipe_author_items.html" with author=author %}
    {% endfor %}
  {% endif %}
</div> 
<nav class="pagination" aria-label="Search results pages">
  <ul class="pagination__container">
    {% if page.has_other_pages %}
      {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
  </ul>
</nav>
{% endblock %}
 </div>

 {% block scripts_js %}
 {% load static %}
 <script src="{% static './js/config/config.js' %}"></script>
 <script src="{% static './js/components/MainCards.js' %}"></script>
 <script src="{% static './js/components/MyFollow.js' %}"></script>
 <script src="{% static './js/components/Subscribe.js' %}"></script>
 <script src="{% static './js/components/Header.js' %}"></script>
 <script src="{% static './js/api/Api.js' %}"></script>
 <script src="{% static 'myFollow.js' %}"></script>
 {% endblock %}

templates/nav.html
{% if user.is_authenticated %}           
  <ul class="nav__items list">
    <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
    <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
  </ul>
{% else %}
  <ul class="nav__items list">
    <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
    <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
  </ul>
{% endif %}   
</div>    
</nav>  


    
        
            
    

templates/paginator.html
{% if items.has_previous %}
  <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.previous_page_number }}&{{filters}}" tabindex="-1" aria-disabled="true"><span class="icon-left"></span></a></li>
{% else %}
  <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.page_number }}&{{ filters }}" ></a></li>     
{% endif %}       
{% for i in paginator.page_range %}
  {% if items.number == i %}
    <li class="pagination__item pagination__item_active"><a class="pagination__link link">{{ i }}  </a></li>
  {% else %}
    <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}&{{ filters }}">{{ i }}</a></li>
  {% endif %}
{% endfor %}
{% if items.has_next %}
  <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.next_page_number }}&{{ filters }}"  tabindex="-1" aria-disabled="true"><span class="icon-right"></span></a></li>
{% else %}
  <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.page_number }}&{{ filters }}"></a></li>
{% endif %}
      

templates/shopList.html
{% extends "base.html" %}
{% block title %} Список покупок  {% endblock %}
{% block main_title %}
<div class="main__header">
  <h1 class="main__title">Список покупок</h1>
</div>
{% endblock %}

{% block static_stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static './pages/shopList.css' %}">
{% endblock static_stylesheet %}

{% block menu %}
{% include "menu.html" with purchase=True %}
{% endblock %}
 
{% block content %}
{% csrf_token %}
<div class="card-list card-list_column">
  <ul class="shopping-list">
    {% for recipe in shops %}
      <li class="shopping-list__item" data-id="{{ recipe.id }}">
        <div class="recipe recipe_reverse">
          <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="recipe__image recipe__image_big">
          <h3 class="recipe__title">{{ recipe.name }}</h3>
          <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
        </div>
        <a href="#" class="shopping-list__button link">Удалить</a>
      </li>
    {% endfor %}
  </ul>
  {% if shops %}
    <a href="{% url  'download_shops' %}"><button class="button button_style_blue">Скачать список</button></a>
  {% endif %}
</div>
{% endblock content %} 

{% block scripts_js %}
{% load static %}
<script src="{% static './js/config/config.js' %}"></script>
<script src="{% static './js/components/ShopList.js' %}"></script>
<script src="{% static './js/components/Header.js' %}"></script>
<script src="{% static './js/api/Api.js' %}"></script>
<script src="{% static 'shopList.js' %}"></script>
{% endblock %}

templates/singlePage.html
{% extends "base.html" %}

{% block title %}{{ recipe.name }}{% endblock %}
{% block main_title %}{% endblock %} 
{% block static_stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static './pages/single.css' %}">
{% endblock static_stylesheet %}

{% block menu %}
{% include "menu.html" with index=True %}
{% endblock %}

{% block content %}
{% csrf_token %} 
<div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">      
  <img  src="{{ recipe.image.url }}" alt="какой-то текст" class="single-card__image" >
  <div class="single-card__info"> 
    <div class="single-card__header-info">
      <h1 class="single-card__title">{{recipe.name}}</h1>
      <div class="single-card__favorite">
        {% if recipe not in favorites %}
          <button class="button button_style_none" name="favorites" data-out>
          <span class="icon-favorite icon-favorite_big"></span></button>
          <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
        {% else %}
          <button class="button button_style_none" name="favorites">
          <span class="icon-favorite icon-favorite_active"></span></button>
        {% endif %}
      </div>
    </div>
    <ul class="single-card__items">
      {% for tag in recipe.tag.all %} 
        {%  if tag.name == 'Завтрак'  %}
          <li class="single-card__item"><span class="badge badge_style_orange">{{ tag.name }}</span></li>                 
        {%  elif tag.name == 'Обед' %} 
          <li class="single-card__item"><span class="badge badge_style_purple">{{ tag.name }}</span></li>
        {%  elif tag.name == 'Ужин' %} 
          <li class="single-card__item"><span class="badge badge_style_green">{{ tag.name }}</span></li>
        {% endif %} 
      {% endfor %}
    </ul> 
    <div class="single-card__items single-card__items_column">
      <p class="single-card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
      <ul class="single-card__items">
        <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span> {{ recipe.author }}</p></li>
        {% if user == recipe.author %}
          <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipe_edit' recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
        {% endif %}
      </ul>
    </div>
    <ul class="single-card__items">
      {% if recipe not in shops %}
        <li class="single-card__item"><button class="button button_style_blue" name="purchases" data-out><span class="icon-plus"></span> Добавить в покупки</button></li>
      {% else %}
        <button class="button button_style_light-blue-outline" name="purchases">
        <span class="icon-check button__icon"></span>Рецепт добавлен</button>
      {% endif %}
      {% if user != recipe.author %}                 
        {% if recipe.author not in subscriptions %}
          <li class="single-card__item"><button class="button button_style_light-blue button_size_subscribe"
          name="subscribe" data-out>Подписаться на автора</button></li>
        {% else %}
          <li class="single-card__item"><button class="button button_style_light-blue button_size_subscribe button_style_blue"
          name="subscribe">Отписаться от автора</button></li>
        {% endif %}
      {% endif %}
    </ul>
    <div class="single-card__section"><h3 class="single-card__section-title">Ингридиенты:</h3>
      <div class="single-card__items single-card__items_column">
        {% for ingredients in recipe.ingredientrecipe_set.all %}
          <p class=" single-card__section-item">{{ ingredients.ingredient.name }} - {{ ingredients.amount }} {{ ingredients.ingredient.dimension }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="single-card__section"><h3 class="single-card__section-title">Описание:</h3>
      <p class=" single-card__section-text">{{ recipe.description|linebreaksbr }}.</p>                 
    </div> 
  </div>
</div>
</div>
{% endblock %}

{% block scripts_js %}
{% load static %}
<script src="{% static './js/components/Purchases.js' %}"></script>
<script src="{% static './js/components/Favorites.js' %}"></script>
<script src="{% static './js/components/Subscribe.js' %}"></script>
<script src="{% static './js/config/config.js' %}"></script>
<script src="{% static './js/components/MainCards.js' %}"></script>
<script src="{% static './js/components/SingleCard.js' %}"></script>
<script src="{% static './js/components/Header.js' %}"></script>
<script src="{% static './js/api/Api.js' %}"></script>
<script src="{% static 'singlePage.js' %}"></script>
{% endblock %}

templates/singlePageNotAuth.html
{% extends "base.html" %}
{% block title %} {{ recipe.name }} {% endblock %}
{% block main_title %}{% endblock %} 

{% block static_stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static './pages/single.css' %}">        
{% endblock static_stylesheet %} 

{% block menu %}
{% include "menu.html" with index=True %}
{% endblock %}   
 
{% block content %}
<div class="single-card" data-id="{{ recipe.id }}">
  <img class="single-card__image" src="{{ recipe.image.url }}" alt="какой-то текст">
  <div class="single-card__info">
    <div class="single-card__header-info"><h1 class="single-card__title">{{ recipe.name }}</h1>
    </div> 
    <ul class="single-card__items">
      {% for tag in recipe.tag.all %}
        {% if tag.name == 'Завтрак' %}
          <li class="single-card__item"><span class="badge badge_style_orange">{{ tag.name }}</span></li>
        {%  elif tag.name == 'Обед' %} 
          <li class="single-card__item"><span class="badge badge_style_purple">{{ tag.name }}</span></li>                    
        {%  elif tag.name == 'Ужин' %} 
          <li class="single-card__item"><span class="badge badge_style_green">{{ tag.name }}</span></li>
        {% endif %} 
      {% endfor %}                
    </ul>
               
    <div class="single-card__items single-card__items_column">
      <p class="single-card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
      <p class="single-card__text"><span class="icon-user"></span> {{ recipe.author }}</p>
    </div>
    <div class="single-card__section"><h3 class="single-card__section-title">Ингридиенты:</h3>
      <div class="single-card__items single-card__items_column">
        {% for ingredients in recipe.ingredientrecipe_set.all %}
          <p class=" single-card__section-item">{{ ingredients.ingredient.name }} - {{ ingredients.amount }} {{ ingredients.ingredient.dimension }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="single-card__section"><h3 class="single-card__section-title">Описание:</h3>
      <p class=" single-card__section-text">{{ recipe.description|linebreaksbr }}</p>
    </div>
  </div>
</div>
{% endblock %}
   
{% block scripts_js %}
{% load static %}
<script src="{% static './js/components/Purchases.js' %}"></script>
<script src="{% static './js/config/config.js' %}"></script>
<script src="{% static './js/components/MainCards.js' %}"></script>
<script src="{% static './js/components/SingleCard.js' %}"></script>
<script src="{% static './js/components/Header.js' %}"></script>
<script src="{% static './js/api/Api.js' %}"></script>
<script src="{% static 'singlePageNotAuth.js' %}"></script>
{% endblock %}      
        